apiVersion: v1
kind: Service
metadata:
  name: jenkins-clusterip
spec:
  selector:
    app: jenkins-pods-service # this name should be available in jenkins pod
  ports:
    - name: first-port
      protocol: TCP
      port: 8081
      targetPort: 8080
