apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: prometheus-daemonset
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus


# Daemon-set is basically used to deploy the pod on each node. It is used while monitoring the cluster.
# also known as monitoring stack
