apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jen-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: jen-server
  template:
    metadata:
      labels:
        type: jen-server
    spec:
      containers:
        - name: jenkins-cont
          image: jenkins/jenkins:lts
