apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: jenkins-daemonset
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
