apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer # provides volume dynamically after pvc is created
reclaimPolicy: Retain
