apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      # ports:
      #   - containerPort: 80


#apiVersion - v1 - version used to create object
#kind - what obeject we are creating
#metadata - used for namming the pod
#spec - components of pod like "containers(for containers er need image& name(optional), ports "
# ports defined in the pod is accessecsable within the cluster only
