apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  labels:
    app: jenkins
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.303.1
      nodeSelector:
        name: worker

# Need to label the node and use that labelled node in nodeselector
# To label node
# kubectl label node <node-name> <label:name>
# kubectl label node ip-10-123-212.compute.im=nternal name=worker
