apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota
  namespace: mynamespace
spec:
  hard:
    pods: "5"
    requests.cpu: "1" # it is used to allocated the cpu in namespace
    requests.memory: "2Gi" # it is used to allocated the memory in namespace
    limits.cpu: "2" # it is used to allocated the maximum cpu in namespace
    limits.memory: "4Gi" # it is used to allocated the maximum memory in namespace
