apiVersion: v1
kind: Pod
metadata:
  name: tomcat-jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8081
    - name: tomcat
      image: tomcat:9.0
      ports:
        - containerPort: 8082

# ports defined in the pod is accessecsable within the cluster only
