apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jen-deployment
  labels:  
    app: jenkins-access
spec:
  replicas: 2
  selector:
    matchLabels:
      type: jen-server
  template:
    metadata:
      labels:
        type: jen-server  # Labels for the Pods created by the Deployment
    spec:
      containers:
        - name: jenkins-cont
          image: jenkins/jenkins:lts
