apiVersion: v1
kind: Service
metadata:
  name: nodeport-jenkins
spec:
  type: NodePort
  selector:
      app: jenkins-pods-service
  ports:
    - name: jenkins-nodeport
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # we need to give from 30000 - 32767 
