apiVersion: v1
kind: Pod
metadata:
  name: pg-database-pod
spec:
  containers:
    - name: pg-database-cont
      image: postgres
      env: 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: username
